[package]
name = "layer-composer"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.8"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
thiserror = "2.0.16"
zip = "5.0.0"
